/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha3

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	infrav1alpha3 "sigs.k8s.io/cluster-api-provider-azure/api/v1alpha3"
	infrav1 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
	clusterv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// Convert_v1alpha3_OSDisk_To_v1beta1_OSDisk is a conversion function.
func Convert_v1alpha3_OSDisk_To_v1beta1_OSDisk(in *infrav1alpha3.OSDisk, out *infrav1.OSDisk, s conversion.Scope) error {
	return infrav1alpha3.Convert_v1alpha3_OSDisk_To_v1beta1_OSDisk(in, out, s)
}

// Convert_v1beta1_OSDisk_To_v1alpha3_OSDisk is a conversion function.
func Convert_v1beta1_OSDisk_To_v1alpha3_OSDisk(in *infrav1.OSDisk, out *infrav1alpha3.OSDisk, s conversion.Scope) error {
	return infrav1alpha3.Convert_v1beta1_OSDisk_To_v1alpha3_OSDisk(in, out, s)
}

// Convert_v1alpha3_Image_To_v1beta1_Image is a conversion function.
func Convert_v1alpha3_Image_To_v1beta1_Image(in *infrav1alpha3.Image, out *infrav1.Image, s conversion.Scope) error {
	return infrav1alpha3.Convert_v1alpha3_Image_To_v1beta1_Image(in, out, s)
}

// Convert_v1beta1_Image_To_v1alpha3_Image is a conversion function.
func Convert_v1beta1_Image_To_v1alpha3_Image(in *infrav1.Image, out *infrav1alpha3.Image, s conversion.Scope) error {
	return infrav1alpha3.Convert_v1beta1_Image_To_v1alpha3_Image(in, out, s)
}

// Convert_v1alpha3_APIEndpoint_To_v1beta1_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha3_APIEndpoint_To_v1beta1_APIEndpoint(in *clusterv1alpha3.APIEndpoint, out *clusterv1.APIEndpoint, s conversion.Scope) error {
	return clusterv1alpha3.Convert_v1alpha3_APIEndpoint_To_v1beta1_APIEndpoint(in, out, s)
}

// Convert_v1beta1_APIEndpoint_To_v1alpha3_APIEndpoint is an autogenerated conversion function.
func Convert_v1beta1_APIEndpoint_To_v1alpha3_APIEndpoint(in *clusterv1.APIEndpoint, out *clusterv1alpha3.APIEndpoint, s conversion.Scope) error {
	return clusterv1alpha3.Convert_v1beta1_APIEndpoint_To_v1alpha3_APIEndpoint(in, out, s)
}
