apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AzureMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-worker
spec:
  template:
    spec:
      osDisk:
        diskSizeGB: 30
        osType: Linux
