name: Dependabot code gen

on:
  pull_request:
    branches:
      - dependabot/**
  push:
    branches:
      - dependabot/**
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for EndBug/add-and-commit
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
      with:
        egress-policy: audit
    - name: Get Go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # tag=v5.0.4
      name: Restore go cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Update all modules
      run: make modules
    - name: Update generated code
      run: make generate
    - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # tag=v10.0.0
      name: Commit changes
      with:
        author_name: dependabot[bot]
        author_email: 49699333+dependabot[bot]@users.noreply.github.com
        default_author: github_actor
        message: 'Update generated code'
